# Generated by Django 6.0.6 on 2026-06-05 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(max_length=50, unique=True)),
                ('total_images', models.IntegerField()),
                ('positive_cases', models.IntegerField()),
                ('negative_cases', models.IntegerField()),
                ('model_accuracy', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('pneumonia', 'Pneumonia'), ('retinopathy', 'Diabetic Retinopathy'), ('skin_cancer', 'Skin Cancer')], max_length=50)),
                ('image', models.ImageField(upload_to='predictions/')),
                ('result', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('prevention_tips', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
